baseURL = "http://nvkp.github.io/4smn/"
languageCode = "cs-CZ"
title = "4SMN Security Management"
enableGitInfo = true

[params]
    BookTheme = 'auto'
    BookDateFormat = '2. 1. 2006'
    BookRepo = 'https://github.com/nvkp/4smn'
